<?php /** @var \Youwe\DataDictionaryBundle\Graph\Entity\Node $node*/ ?>
<table border="0" cellborder="0"  cellspacing="0">
    <tr><td colspan="3" align="center"><u><b><?=$node->getName()?></b></u></td></tr>
    <?php foreach($node->getAttributes() as $attribute): ?>
    <tr>
        <td align="left"><?= $attribute->getName(); ?></td>
        <td><b><?= $attribute->isMandatory() ? 'M' : '&nbsp;' ?></b></td>
        <td><b><?= $attribute->isUnique() ? 'U' : '&nbsp;' ?></b></td>
    </tr>
    <?php endforeach; ?>
</table>